modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"
[[mods]]
modId="mcw_tfc_aio"
version="${mod_version}"
displayName="Macaw's All-In-One for TFC"
authors="ArcWolfGaming" #optional
description='''Updates Macaw's Mods to include TerraFirmaCraft Blocks'''


[[dependencies.mcw_tfc_aio]]
modId="tfc"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mcw_tfc_aio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "AFTER"
side = "BOTH"