//
//public static final RegistryObject<Item> OAK_WARDROBE = ITEMS.register("furniture/oak_furniture/oak_wardrobe", () -> new ItemBlock(FurnitureInit.OAK_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_MODERN_WARDROBE = ITEMS.register("furniture/oak_furniture/oak_modern_wardrobe", () -> new ItemBlock(FurnitureInit.OAK_MODERN_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DOUBLE_WARDROBE = ITEMS.register("furniture/oak_furniture/oak_double_wardrobe", () -> new ItemBlock(FurnitureInit.OAK_DOUBLE_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_BOOKSHELF = ITEMS.register("furniture/oak_furniture/oak_bookshelf", () -> new ItemBlock(FurnitureInit.OAK_BOOKSHELF.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_BOOKSHELF_CUPBOARD = ITEMS.register("furniture/oak_furniture/oak_bookshelf_cupboard", () -> new ItemBlock(FurnitureInit.OAK_BOOKSHELF_CUPBOARD.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DRAWER = ITEMS.register("furniture/oak_furniture/oak_drawer", () -> new ItemBlock(FurnitureInit.OAK_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DOUBLE_DRAWER = ITEMS.register("furniture/oak_furniture/oak_double_drawer", () -> new ItemBlock(FurnitureInit.OAK_DOUBLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_BOOKSHELF_DRAWER = ITEMS.register("furniture/oak_furniture/oak_bookshelf_drawer", () -> new ItemBlock(FurnitureInit.OAK_BOOKSHELF_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_LOWER_BOOKSHELF_DRAWER = ITEMS.register("furniture/oak_furniture/oak_lower_bookshelf_drawer", () -> new ItemBlock(FurnitureInit.OAK_LOWER_BOOKSHELF_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_LARGE_DRAWER = ITEMS.register("furniture/oak_furniture/oak_large_drawer", () -> new ItemBlock(FurnitureInit.OAK_LARGE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_LOWER_TRIPLE_DRAWER = ITEMS.register("furniture/oak_furniture/oak_lower_triple_drawer", () -> new ItemBlock(FurnitureInit.OAK_LOWER_TRIPLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_TRIPLE_DRAWER = ITEMS.register("furniture/oak_furniture/oak_triple_drawer", () -> new ItemBlock(FurnitureInit.OAK_TRIPLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DESK = ITEMS.register("furniture/oak_furniture/oak_desk", () -> new ItemBlock(FurnitureInit.OAK_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_COVERED_DESK = ITEMS.register("furniture/oak_furniture/oak_covered_desk", () -> new ItemBlock(FurnitureInit.OAK_COVERED_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_MODERN_DESK = ITEMS.register("furniture/oak_furniture/oak_modern_desk", () -> new ItemBlock(FurnitureInit.OAK_MODERN_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_TABLE = ITEMS.register("furniture/oak_furniture/oak_table", () -> new ItemBlock(FurnitureInit.OAK_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_END_TABLE = ITEMS.register("furniture/oak_furniture/oak_end_table", () -> new ItemBlock(FurnitureInit.OAK_END_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_COFFEE_TABLE = ITEMS.register("furniture/oak_furniture/oak_coffee_table", () -> new ItemBlock(FurnitureInit.OAK_COFFEE_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_GLASS_TABLE = ITEMS.register("furniture/oak_furniture/oak_glass_table", () -> new ItemBlock(FurnitureInit.OAK_GLASS_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_CHAIR = ITEMS.register("furniture/oak_furniture/oak_chair", () -> new ItemBlock(FurnitureInit.OAK_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_MODERN_CHAIR = ITEMS.register("furniture/oak_furniture/oak_modern_chair", () -> new ItemBlock(FurnitureInit.OAK_MODERN_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_STRIPED_CHAIR = ITEMS.register("furniture/oak_furniture/oak_striped_chair", () -> new ItemBlock(FurnitureInit.OAK_STRIPED_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_STOOL_CHAIR = ITEMS.register("furniture/oak_furniture/oak_stool_chair", () -> new ItemBlock(FurnitureInit.OAK_STOOL_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_COUNTER = ITEMS.register("furniture/oak_furniture/oak_counter", () -> new ItemBlock(FurnitureInit.OAK_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DRAWER_COUNTER = ITEMS.register("furniture/oak_furniture/oak_drawer_counter", () -> new ItemBlock(FurnitureInit.OAK_DRAWER_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_DOUBLE_DRAWER_COUNTER = ITEMS.register("furniture/oak_furniture/oak_double_drawer_counter", () -> new ItemBlock(FurnitureInit.OAK_DOUBLE_DRAWER_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> OAK_CUPBOARD_COUNTER = ITEMS.register("furniture/oak_furniture/oak_cupboard_counter", () -> new ItemBlock(FurnitureInit.OAK_CUPBOARD_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_WARDROBE = ITEMS.register("furniture/oak_furniture/stripped_oak_wardrobe", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_MODERN_WARDROBE = ITEMS.register("furniture/oak_furniture/stripped_oak_modern_wardrobe", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_MODERN_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DOUBLE_WARDROBE = ITEMS.register("furniture/oak_furniture/stripped_oak_double_wardrobe", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DOUBLE_WARDROBE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_BOOKSHELF = ITEMS.register("furniture/oak_furniture/stripped_oak_bookshelf", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_BOOKSHELF.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_BOOKSHELF_CUPBOARD = ITEMS.register("furniture/oak_furniture/stripped_oak_bookshelf_cupboard", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_BOOKSHELF_CUPBOARD.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DOUBLE_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_double_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DOUBLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_BOOKSHELF_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_bookshelf_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_BOOKSHELF_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_lower_bookshelf_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_LARGE_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_large_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_LARGE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_LOWER_TRIPLE_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_lower_triple_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_LOWER_TRIPLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_TRIPLE_DRAWER = ITEMS.register("furniture/oak_furniture/stripped_oak_triple_drawer", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_TRIPLE_DRAWER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DESK = ITEMS.register("furniture/oak_furniture/stripped_oak_desk", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_COVERED_DESK = ITEMS.register("furniture/oak_furniture/stripped_oak_covered_desk", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_COVERED_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_MODERN_DESK = ITEMS.register("furniture/oak_furniture/stripped_oak_modern_desk", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_MODERN_DESK.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_TABLE = ITEMS.register("furniture/oak_furniture/stripped_oak_table", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_END_TABLE = ITEMS.register("furniture/oak_furniture/stripped_oak_end_table", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_END_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_COFFEE_TABLE = ITEMS.register("furniture/oak_furniture/stripped_oak_coffee_table", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_COFFEE_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_GLASS_TABLE = ITEMS.register("furniture/oak_furniture/stripped_oak_glass_table", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_GLASS_TABLE.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_CHAIR = ITEMS.register("furniture/oak_furniture/stripped_oak_chair", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_MODERN_CHAIR = ITEMS.register("furniture/oak_furniture/stripped_oak_modern_chair", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_MODERN_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_STRIPED_CHAIR = ITEMS.register("furniture/oak_furniture/stripped_oak_striped_chair", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_STRIPED_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_STOOL_CHAIR = ITEMS.register("furniture/oak_furniture/stripped_oak_stool_chair", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_STOOL_CHAIR.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_COUNTER = ITEMS.register("furniture/oak_furniture/stripped_oak_counter", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DRAWER_COUNTER = ITEMS.register("furniture/oak_furniture/stripped_oak_drawer_counter", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DRAWER_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_DOUBLE_DRAWER_COUNTER = ITEMS.register("furniture/oak_furniture/stripped_oak_double_drawer_counter", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_DOUBLE_DRAWER_COUNTER.get(), new Item.Properties()));
//public static final RegistryObject<Item> STRIPPED_OAK_CUPBOARD_COUNTER = ITEMS.register("furniture/oak_furniture/stripped_oak_cupboard_counter", () -> new ItemBlock(FurnitureInit.STRIPPED_OAK_CUPBOARD_COUNTER.get(), new Item.Properties()));
//
//
//
//        pOutput.accept(FurnitureInit.OAK_WARDROBE.get());
//        pOutput.accept(FurnitureInit.OAK_CHAIR.get());
//        pOutput.accept(FurnitureInit.OAK_MODERN_WARDROBE.get());
//        pOutput.accept(FurnitureInit.OAK_DOUBLE_WARDROBE.get());
//        pOutput.accept(FurnitureInit.OAK_BOOKSHELF.get());
//        pOutput.accept(FurnitureInit.OAK_BOOKSHELF_CUPBOARD.get());
//        pOutput.accept(FurnitureInit.OAK_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_DOUBLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_BOOKSHELF_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_LOWER_BOOKSHELF_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_LARGE_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_LOWER_TRIPLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_TRIPLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.OAK_DESK.get());
//        pOutput.accept(FurnitureInit.OAK_COVERED_DESK.get());
//        pOutput.accept(FurnitureInit.OAK_MODERN_DESK.get());
//        pOutput.accept(FurnitureInit.OAK_TABLE.get());
//        pOutput.accept(FurnitureInit.OAK_END_TABLE.get());
//        pOutput.accept(FurnitureInit.OAK_COFFEE_TABLE.get());
//        pOutput.accept(FurnitureInit.OAK_GLASS_TABLE.get());
//        pOutput.accept(FurnitureInit.OAK_CHAIR.get());
//        pOutput.accept(FurnitureInit.OAK_MODERN_CHAIR.get());
//        pOutput.accept(FurnitureInit.OAK_STRIPED_CHAIR.get());
//        pOutput.accept(FurnitureInit.OAK_STOOL_CHAIR.get());
//        pOutput.accept(FurnitureInit.OAK_COUNTER.get());
//        pOutput.accept(FurnitureInit.OAK_DRAWER_COUNTER.get());
//        pOutput.accept(FurnitureInit.OAK_DOUBLE_DRAWER_COUNTER.get());
//        pOutput.accept(FurnitureInit.OAK_CUPBOARD_COUNTER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_WARDROBE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_MODERN_WARDROBE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DOUBLE_WARDROBE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_BOOKSHELF.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_BOOKSHELF_CUPBOARD.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DOUBLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_BOOKSHELF_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_LARGE_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_LOWER_TRIPLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_TRIPLE_DRAWER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DESK.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_COVERED_DESK.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_MODERN_DESK.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_TABLE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_END_TABLE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_COFFEE_TABLE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_GLASS_TABLE.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_CHAIR.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_MODERN_CHAIR.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_STRIPED_CHAIR.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_STOOL_CHAIR.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_COUNTER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DRAWER_COUNTER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_DOUBLE_DRAWER_COUNTER.get());
//        pOutput.accept(FurnitureInit.STRIPPED_OAK_CUPBOARD_COUNTER.get());
//
//
//public static final RegistryObject<Block> OAK_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_wardrobe", () -> new TallFurnitureHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_MODERN_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_modern_wardrobe", () -> new TallFurnitureHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DOUBLE_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_double_wardrobe", () -> new TallFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_BOOKSHELF = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_bookshelf", () -> new BookCabinet(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_BOOKSHELF_CUPBOARD = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_bookshelf_cupboard", () -> new BookCabinetHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DOUBLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_double_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_BOOKSHELF_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_bookshelf_drawer", () -> new BookDrawer(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_LOWER_BOOKSHELF_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_lower_bookshelf_drawer", () -> new BookDrawer(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_LARGE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_large_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_LOWER_TRIPLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_lower_triple_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_TRIPLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_triple_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_COVERED_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_covered_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_MODERN_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_modern_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_END_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_end_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_COFFEE_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_coffee_table", () -> new Table(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_GLASS_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_glass_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_chair", () -> new ClassicChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_MODERN_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_modern_chair", () -> new ModernChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_STRIPED_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_striped_chair", () -> new StripedChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_STOOL_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_stool_chair", () -> new Chair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_counter", () -> new Counter(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DRAWER_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_drawer_counter", () -> new StorageCounter(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_DOUBLE_DRAWER_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_double_drawer_counter", () -> new StorageCounter(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> OAK_CUPBOARD_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/oak_cupboard_counter", () -> new CupboardCounter(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_wardrobe", () -> new TallFurnitureHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_MODERN_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_modern_wardrobe", () -> new TallFurnitureHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DOUBLE_WARDROBE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_double_wardrobe", () -> new TallFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_BOOKSHELF = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_bookshelf", () -> new BookCabinet(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_BOOKSHELF_CUPBOARD = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_bookshelf_cupboard", () -> new BookCabinetHinge(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DOUBLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_double_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_BOOKSHELF_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_bookshelf_drawer", () -> new BookDrawer(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_lower_bookshelf_drawer", () -> new BookDrawer(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_LARGE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_large_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_LOWER_TRIPLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_lower_triple_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_TRIPLE_DRAWER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_triple_drawer", () -> new WideFurniture(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_COVERED_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_covered_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_MODERN_DESK = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_modern_desk", () -> new Desk(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_END_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_end_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_COFFEE_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_coffee_table", () -> new Table(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_GLASS_TABLE = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_glass_table", () -> new TableHitbox(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_chair", () -> new ClassicChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_MODERN_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_modern_chair", () -> new ModernChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_STRIPED_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_striped_chair", () -> new StripedChair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_STOOL_CHAIR = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_stool_chair", () -> new Chair(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_counter", () -> new Counter(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DRAWER_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_drawer_counter", () -> new StorageCounter(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_DOUBLE_DRAWER_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_double_drawer_counter", () -> new StorageCounter(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
//public static final RegistryObject<Block> STRIPPED_OAK_CUPBOARD_COUNTER = BLOCKS_FURNITURE.register("furniture/oak_furniture/stripped_oak_cupboard_counter", () -> new CupboardCounter(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0F, 2.3F)));
