package com.mcw_tfc_aio.arcwolf.init;

import com.mcw_tfc_aio.arcwolf.Mcw_Tfc_Aio;
import com.mcw_tfc_aio.arcwolf.objects.gutters.GutterTall;
import com.mcw_tfc_aio.arcwolf.objects.gutters.RainGutter;
import com.mcw_tfc_aio.arcwolf.objects.roofs.AwningBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Map;

public class GutterInit {

    // public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Mcw_Tfc_Aio.MOD_ID);
     public static final DeferredRegister<Block> BLOCKS_GUTTERS = DeferredRegister.create(ForgeRegistries.BLOCKS, Mcw_Tfc_Aio.MOD_ID);
    public static final RegistryObject<Block> GUTTER_MIDDLE = BLOCKS_GUTTERS.register("roofs/awnings/gutter_middle", () ->  new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	BLACK_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/black_striped_awning", () -> new AwningBlock(Blocks.BLACK_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	BLUE_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/blue_striped_awning", () -> new AwningBlock(Blocks.BLUE_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLUE).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	BROWN_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/brown_striped_awning", () -> new AwningBlock(Blocks.BROWN_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BROWN).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	CYAN_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/cyan_striped_awning", () -> new AwningBlock(Blocks.CYAN_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_CYAN).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	GRAY_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/gray_striped_awning", () -> new AwningBlock(Blocks.GRAY_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GRAY).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	GREEN_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/green_striped_awning", () -> new AwningBlock(Blocks.GREEN_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	LIGHT_BLUE_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/light_blue_striped_awning", () -> new AwningBlock(Blocks.LIGHT_BLUE_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_BLUE).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	LIGHT_GRAY_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/light_gray_striped_awning", () -> new AwningBlock(Blocks.LIGHT_GRAY_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	LIME_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/lime_striped_awning", () -> new AwningBlock(Blocks.LIME_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GREEN).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	MAGENTA_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/magenta_striped_awning", () -> new AwningBlock(Blocks.MAGENTA_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	ORANGE_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/orange_striped_awning", () -> new AwningBlock(Blocks.ORANGE_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_ORANGE).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	PINK_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/pink_striped_awning", () -> new AwningBlock(Blocks.PINK_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PINK).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	PURPLE_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/purple_striped_awning", () -> new AwningBlock(Blocks.PURPLE_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	RED_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/red_striped_awning", () -> new AwningBlock(Blocks.RED_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	YELLOW_STRIPED_AWNING = BLOCKS_GUTTERS.register("roofs/awnings/yellow_striped_awning", () -> new AwningBlock(Blocks.YELLOW_WOOL.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).noOcclusion().strength(0.6F, 1.3F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block>	GUTTER_BASE_YELLOW = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_yellow", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_YELLOW).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_ORANGE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_orange", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_ORANGE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_RED = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_red", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_RED).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_PINK = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_pink", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_PINK).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_MAGENTA = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_magenta", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_MAGENTA).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_PURPLE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_purple", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_PURPLE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_LIGHT_BLUE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_light_blue", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_BLUE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_BLUE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_blue", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BLUE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_CYAN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_cyan", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_CYAN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_LIME = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_lime", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_GREEN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_GREEN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_green", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_GREEN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_BROWN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_brown", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BROWN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_CYAN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_BLACK = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_black", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BLACK).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_GRAY = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_gray", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_GRAY).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_LIGHT_GRAY = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_light_gray", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_BASE_WHITE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_base_white", () -> new RainGutter(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_WHITE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_YELLOW = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_yellow", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_YELLOW).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_ORANGE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_orange", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_ORANGE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_RED = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_red", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_RED).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_PINK = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_pink", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_PINK).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_MAGENTA = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_magenta", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_MAGENTA).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_PURPLE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_purple", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_PURPLE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_LIGHT_BLUE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_light_blue", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_BLUE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_BLUE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_blue", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BLUE).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_CYAN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_cyan", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_CYAN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_LIME = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_lime", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_GREEN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_GREEN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_green", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_GREEN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_BROWN = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_brown", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BROWN).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_BLACK = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_black", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_BLACK).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_GRAY = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_gray", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_GRAY).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_LIGHT_GRAY = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_light_gray", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).strength(1.3F, 2.3F).sound(SoundType.METAL)));
    public static final RegistryObject<Block>	GUTTER_MIDDLE_WHITE = BLOCKS_GUTTERS.register("roofs/gutters/gutter_middle_white", () -> new GutterTall(Blocks.IRON_BLOCK.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_WHITE).strength(1.3F, 2.3F).sound(SoundType.METAL)));

}
